#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(input().strip())
    if n%2 != 0: #odd
        print("Weird")
    else: #even 
        if n in range(2, 6): #in range of 2 and 5
            print("Not Weird")
        elif n in range(6, 21): #in range of 6 and 21
            print("Weird")
        else: #greater than 20
            print("Not Weird")
